ProiectMaster.Web/Models/ErrorViewModel.cs
using System;

namespace ProiectMaster.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProiectMaster.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProiectMaster.Models.Interfaces;
using System.Collections.Generic;

namespace ProiectMaster.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService productService;

        public HomeController(IProductService productService)
        {
            this.productService = productService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var products = productService.GetAllProducts();
            return View(products);
        }

        [HttpGet]
        [Route("Details/{id}")]
        public IActionResult Details(int id)
        {
            var product = productService.GetProduct(id);
            return View(product);
        }

        [HttpPost]
        [Route("Add/{id}")]
        public IActionResult Add(int id)
        {
            var shopList = HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);

            if (shopList == null)
                shopList = new List<int>();

            if (!shopList.Contains(id))
                shopList.Add(id);

            HttpContext.Session.Set(SessionHelper.ShoppingCart, shopList);

            return RedirectToAction("Index", "Home", productService.GetAllProducts());
        }

        [HttpPost]
        [Route("Remove/{id}")]
        public IActionResult Remove(int id)
        {
            var shopList = HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);

            if (shopList == null)
                return RedirectToAction("Index", "Home", productService.GetAllProducts());

            if (shopList.Contains(id))
                shopList.Remove(id);

            HttpContext.Session.Set(SessionHelper.ShoppingCart, shopList);

            return RedirectToAction("Index", "Home", productService.GetAllProducts());
        }
    }
}

ProiectMaster.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using ProiectMaster.Models.DTOs.VM;
using ProiectMaster.Models.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProiectMaster.Web.Controllers
{
    [Route("[Controller]")]
    public class ProductController : Controller
    {
        private readonly IProductService service;

        public ProductController(IProductService service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = service.GetAllProducts();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var dto = new ProductVM();
            dto.ProductTypes = service.GetProductTypes();
            return View(dto);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult New(ProductVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                dto.ProductTypes = service.GetProductTypes();
                return View(dto);
            }

            service.AddProduct(dto);

            return View("Index", service.GetAllProducts());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var dto = service.GetProduct(id);
            dto.ProductTypes = service.GetProductTypes();
            return View(dto);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, ProductVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                dto.ProductTypes = service.GetProductTypes();
                return View(dto);
            }

            service.UpdateProduct(id, dto);

            return View("Index", service.GetAllProducts());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            service.DeleteProduct(id);
            return Json(new { success = true, message = "Delete success" });
        }
    }
}

ProiectMaster.Web/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using ProiectMaster.Models.DTOs.VM;
using ProiectMaster.Models.Interfaces;

namespace ProiectMaster.Web.Controllers
{
    [Route("[Controller]")]
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeService service;

        public ProductTypeController(IProductTypeService service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = service.GetAllProductType();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var dto = new ProductTypeVM();
            return View(dto);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult New(ProductTypeVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(dto);
            }

            service.AddProductType(dto);

            return View("Index", service.GetAllProductType());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var dto = service.GetProductType(id);
            return View(dto);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, ProductTypeVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(dto);
            }

            service.UpdateProductType(id, dto);

            return View("Index", service.GetAllProductType());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            service.DeleteProductType(id);
            return Json(new { success = true, message = "Delete success" });
        }
    }
}

ProiectMaster.Web/Views/Home/Details.cshtml
@model ProductVM

@inject IHttpContextAccessor HttpContextAccessor
@{ 
    bool isInBag = false;
    var lstCart = HttpContextAccessor.HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);
    if (lstCart != null && lstCart.Contains(Model.Id))
        isInBag = true;

    var route = isInBag ? "/Remove/{0}" : "/Add/{0}";
    route = string.Format(route, Model.Id);
}

<h2 class="text-info">Product Details</h2>

<form action="@route" method="post">

    <div class="p-4 border rounded row">
        <div class="col-8">

            <div class="form-group row">
                <div class="col-4">
                    <label>Product name</label>
                </div>
                <div class="col-4">
                    <input asp-for="Name" readonly class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label>Price</label>
                </div>
                <div class="col-4">
                    <input asp-for="Price" readonly class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label>Description</label>
                </div>
                <div class="col-4">
                    @Html.TextArea("Description", Model.Description, new { @class = "form-control", @readonly="readonly" })
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4"></div>
                <div class="col-8">
                    @if (isInBag)
                    {
                        <button type="submit" value="Remove from bag" class="btn btn-danger form-control">Remove from Bag</button>
                    }
                    else
                    {
                        <button type="submit" value="Add to bag" class="btn btn-primary form-control">Add to Bag</button>
                    }
                </div>
            </div>

        </div>

        <div class=" col-1">

        </div>

        <div class="col-3">
            <img src="~/@Model.ImagePath" alt="no image" width="100%" style="border-radius:5px; border:1px solid #bbb9b9;" />
        </div>
    </div>

    <br/>

    <div class="form-group">
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>

</form>

ProiectMaster.Web/Views/Home/Index.cshtml
@model IEnumerable<ProductVM>

@{
    ViewData["Title"] = "Home Page";
    var detailsRoute = "/Details/{0}";
}

<div class="row">

    @foreach( var product in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="card mb-4">

                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size:23px; color:steelblue;">@product.Name</label>
                    </h4>
                </div>

                <img class="card-img-top" style="height:100%" src="~/@product.ImagePath" alt="no image" />

                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:20px; color:#a51313"><b>$@product.Price</b></label>
                        </div>
                        <a href="@string.Format(detailsRoute, product.Id)" class="btn pull-right btn-outline-info">View Details</a>
                    </div>
                </div>

            </div>
        </div>
    }

</div>

ProiectMaster.Web/Views/Product/Edit.cshtml
@model ProductVM

@{
    ViewData["Title"] = "Edit a product";
}

@{ ViewBag.IsNew = false;}

@await Html.PartialAsync(@"../Shared/Components/_Product.cshtml")

ProiectMaster.Web/Views/Product/Index.cshtml
@model IEnumerable<ProductVM>

@{
    ViewData["Title"] = "Product";
}

<div class="row mb-2 mt-2 operationsButtons">
    <div class="col-md-12">
        <a href="/Product/New" class="btn btn-new btn-outline-new font-weight-bold mr-2" data-toggle="tooltip" title="New" data-placement="top">
            <span class="fa fa-plus-circle"></span>
        </a>

        <button class="btn btn-outline-dark font-weight-bold mr-2" data-toggle="tooltip" title="Edit" data-placement="top" onclick="Product.onEditBtnPress()">
            <span class="fa fa-edit"></span>
        </button>

        <button type="button" class="btn btn-delete btn-outline-delete font-weight-bold mr-2" id="btnDelete" data-toggle="tooltip" data-placement="top" title="Delete" onclick="Product.onDelete()">
            <span class="fa fa-trash"></span>
        </button>
    </div>
</div>

<br/><br/>

     <table id="table" class="table table-hover table-striped table-dark">
         <thead>
             <tr>
                 <th hidden>Product Id</th>
                 <th>Image</th>
                 <th>Product name</th>
                 <th>Description</th>
                 <th>Price</th>
                 <th>Is in stoc</th>
             </tr>
         </thead>

         <tbody>

             @foreach (var item in Model)
              {
             <tr id="@item.Id">
                 <td hidden>@item.Id</td>
                 <td><img style="width: 300px; height: 150px;" src="~/@item.ImagePath" alt="nu exista imagine momentan" /></td>
                 <td>@item.Name</td>
                 <td>@item.Description</td>
                 <td>@item.Price</td>
                 <td><input type="checkbox" disabled checked="@item.IsAvailable" /></td>
             </tr>
              }

         </tbody>

     </table>

ProiectMaster.Web/Views/Product/New.cshtml
@model ProductVM

@{
    ViewData["Title"] = "Create a product";
}

@{ ViewBag.IsNew = true;}

@await Html.PartialAsync(@"../Shared/Components/_Product.cshtml")

ProiectMaster.Web/Views/ProductType/Edit.cshtml
@model ProductTypeVM

@{
    ViewData["Title"] = "Edit a product Type";
}

@{ ViewBag.IsNew = false;}

@await Html.PartialAsync(@"../Shared/Components/_ProductType.cshtml")

ProiectMaster.Web/Views/ProductType/Index.cshtml
@model IEnumerable<ProductTypeVM>;

@{ 
    ViewData["Title"] = "Product Type";
}

<div class="row mb-2 mt-2 operationsButtons">
    <div class="col-md-12">
        <a href="/ProductType/New" class="btn btn-new btn-outline-new font-weight-bold mr-2" data-toggle="tooltip" title="New" data-placement="top">
            <span class="fa fa-plus-circle"></span>
        </a>

        <button class="btn btn-outline-dark font-weight-bold mr-2" data-toggle="tooltip" title="Edit" data-placement="top" onclick="ProductType.onEditBtnPress()" >
            <span class="fa fa-edit"></span>
        </button>

        <button type="button" class="btn btn-delete btn-outline-delete font-weight-bold mr-2" id="btnDelete" data-toggle="tooltip" data-placement="top" title="Delete" onclick="ProductType.onDelete()">
            <span class="fa fa-trash"></span>
        </button>
    </div>
</div>

<table id="table" class="table table-hover table-striped table-dark">
    <thead>
        <tr>
            <th hidden>Product Type Id</th>
            <th>Product Type name</th>
        </tr>
    </thead>

    <tbody>

        @foreach(var item in Model)
        { 
            <tr id="@item.Id">
                <td hidden>@item.Id</td>
                <td>@item.Name</td>
            </tr>
         }

    </tbody>

</table>

ProiectMaster.Web/Views/ProductType/New.cshtml
@model ProductTypeVM

@{
    ViewData["Title"] = "Create a product Type";
}

@{ ViewBag.IsNew = true;}

@await Html.PartialAsync(@"../Shared/Components/_ProductType.cshtml")

ProiectMaster.Web/Views/Shared/Components/_CancelSaveBtn.cshtml
<div class="col-sm-12 text-center">
    <br />
    <a class=" btn btn-danger" style="width: 100px" asp-action="Index"><em class="fas fa-undo-alt"></em> Cancel</a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button type="submit" style="width: 100px" class="btn btn-success"><em class="fas fa-save"></em> Save</button>
</div>

ProiectMaster.Web/Views/Shared/Components/_Product.cshtml
@model ProductVM

@{
    string action = "";
    var isNew = (bool)ViewBag.IsNew;
    if (isNew)
        action = "/Product/New";
    else
        action = string.Format("/Product/Edit/{0}", Model.Id);
}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 table-round bg-light shadow">

        <br />
        <h4>Product type</h4>
        <br />

        <div class="col-xl-12">

            <input asp-for="Id" hidden />

            <form action="@action" method="post" enctype="multipart/form-data">

                <div asp-validation-summary="All" class="text-danger"></div>
                <br />
                <div class="row">

                    <div class="col-sm-12 col-lg-12">

                        <div class="row">

                            <div class="col-xs-12 col-sm-2">
                                <label class="control-label font-weight-bold">Product name</label>
                            </div>

                            <div class="col-xs-12 col-sm-4">
                                <input asp-for="Name" class="form-control" /><br />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="col-xs-12 col-sm-2">
                                <label class="control-label font-weight-bold">Price</label>
                            </div>

                            <div class="col-xs-12 col-sm-4">
                                <input asp-for="Price" class="form-control" /><br />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="row">

                            <div class="col-xs-12 col-sm-2">
                                <label class="control-label font-weight-bold">Is available</label>
                            </div>

                            <div class="col-xs-12 col-sm-4">
                                <input type="checkbox" asp-for="IsAvailable" /><br />
                                <span asp-validation-for="IsAvailable" class="text-danger"></span>
                            </div>

                            <div class="col-xs-12 col-sm-2">
                                <label class="control-label font-weight-bold">Product type</label>
                            </div>

                            <div class="col-xs-12 col-sm-4">
                                @Html.DropDownList("ProductTypeId", new SelectList(Model.ProductTypes, "Id", "Name", Model.ProductTypeId), new { @class = "form-control" })
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>

                        </div>

                        <br />

                        <div class="row">

                            <div class="col-xs-12 col-sm-2">
                                <label class="control-label font-weight-bold">Upload a image</label>
                            </div>

                            <div class="col-xs-12 col-sm-4">
                                <input id="fileInput" type="file" asp-for="ProducImage" class="custom-file-input" onchange="Product.onChangeFile(event)" /><br />
                                <label id="fileUploadlabel" class="custom-file-label" for="fileInput">Choose file</label>
                                <span asp-validation-for="ProducImage" class="text-danger"></span>
                            </div>

                        </div>

                        <br />

                        <div class="row">

                            <div class="col-xs-12 col-sm-2">
                                <label class="control-label font-weight-bold">Description</label>
                            </div>

                            <div class="col-xs-12 col-sm-10">
                                @Html.TextArea("Description", Model.Description, new { @class = "form-control" })
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                        </div>

                        <br />

                        @if (!isNew)
                        {

                            <div class="row">

                                <div class="col-xs-12 col-sm-2">
                                    <label class="control-label font-weight-bolg">Product image</label>
                                </div>

                                <div class="col-xs-12 col-sm-10">
                                   <img style="width:300px; height:150px;" src="~/@Model.ImagePath" alt="nu exista imagine peste acest produs" />
                                </div>

                            </div>

                        }

                    </div>

                    @await Html.PartialAsync(@"_CancelSaveBtn.cshtml");

                </div>

            </form>

        </div>

    </div>
</div>

ProiectMaster.Web/Views/Shared/Components/_ProductType.cshtml
@model ProductTypeVM

@{ 
    string action = "";
    if ((bool)ViewBag.IsNew)
        action = "/ProductType/New";
    else
        action = string.Format("/ProductType/Edit/{0}", Model.Id);

}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 table-round bg-light shadow">

        <br/>
        <h4>Product type</h4>
        <br/>

        <div class="col-xl-12">
            
            <input asp-for="Id" hidden />

            <form action="@action" method="post">

                <div asp-validation-summary="All" class="text-danger"></div>
                <br/>
                <div class="row">

                    <div class="col-sm-12 col-lg-6">
                        <div class="row">

                            <div class="col-xs-12 col-sm-4">
                                <label class="control-label font-weight-bold">Product type name</label>
                            </div>

                            <div class="col-xs-12 col-sm-6">
                                <input asp-for="Name" class="form-control" /><br/>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                        </div>

                    </div>

                    @await Html.PartialAsync(@"_CancelSaveBtn.cshtml"); 

                </div>

            </form>

        </div>

    </div>
</div>

ProiectMaster.Web/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@{ 
    var shoppingList = HttpContextAccessor.HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);
    var shoppingCount = shoppingList == null ? 0 : shoppingList.Count;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProiectMaster.Web</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/js/site.js"></script>

    <script src="~/js/productType.js"></script>
    <script src="~/js/product.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="160" height="90" src="https://img.freepik.com/premium-vector/fast-food-logo-design-vector_18099-221.jpg?w=2000"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ProductType" asp-action="Index">Product type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white"><span class="fas fa-shopping-cart"></span> &nbsp; (@shoppingCount)</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-danger">
        <div class="container text-white">
            &copy; 2022 - ProiectMaster.Web - Toma Radu-Cristian
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>